spring:
  application:
    name: kafka-core-producer
---
logging:
  pattern:
    console: "[Kafka Core Producer] %clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(---){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"

spring:
  main:
    banner-mode: OFF
  jackson:
    date-format: yyyy-MMM-dd
#  kafka:
#    producer:
#      bootstrap-servers: localhost:19092