spring:
  application:
    name: kafka-core-consumer
server:
  port: 10080
---
logging:
  pattern:
    console: "[Consumer %t] %clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(---){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"

spring:
  main:
    banner-mode: OFF
  jackson:
    date-format: yyyy-MMM-dd
  kafka:
    consumer:
      group-id: default-spring-consumer
      bootstrap-servers: localhost:19092
      auto-offset-reset: earliest
